const ALL: &[&str] = &[
    "Clock speed too slow.",
    "Solar flares.",
    "Electromagnetic radiation from satellite debris.",
    "Static from nylon underwear.",
    "Static from plastic slide rules.",
    "Global warming.",
    "Poor power conditioning.",
    "Static buildup.",
    "Doppler effect.",
    "Hardware stress fractures.",
    "Magnetic interference from money/credit cards.",
    "Dry joints on cable plug.",
    "We're waiting for [the phone company] to fix that line.",
    "Sounds like a Windows problem try calling Microsoft support.",
    "Temporary routing anomaly.",
    "Somebody was calculating pi on the server.",
    "Fat electrons in the lines.",
    "Excess surge protection.",
    "Floating point processor overflow.",
    "Divide-by-zero error.",
    "POSIX compliance problem.",
    "Monitor resolution too high.",
    "Improperly oriented keyboard.",
    "Network packets traveling uphill (use a carrier pigeon).",
    "Decreasing electron flux.",
    "First Saturday after first full moon in Winter.",
    "Radiosity depletion.",
    "CPU radiator broken.",
    "It works the way the Wang did, what's the problem?",
    "Positron router malfunction.",
    "Cellular telephone interference.",
    "Techtonic stress.",
    "Piezo-electric interference.",
    "(L)User error.",
    "Working as designed.",
    "Dynamic software linking table corrupted.",
    "Heavy gravity fluctuation, move computer to floor rapidly.",
    "Secretary plugged hairdryer into UPS.",
    "Terrorist activities.",
    "Not enough memory to get system upgrade.",
    "Interrupt configuration error.",
    "Spaghetti cable cause packet failure.",
    "Boss forgot system password.",
    "Bank holiday - system operating credits not recharged.",
    "Virus attack, luser responsible.",
    "Waste water tank overflowed onto computer.",
    "Complete Transient Lockout.",
    "Bad ether in the cables.",
    "Bogon emissions.",
    "Change in Earth's rotational speed.",
    "Cosmic ray particles crashed through the hard disk platter.",
    "Smell from unhygienic janitorial staff wrecked the tape heads.",
    "Hamster in running wheel had coronary; awaiting Fedex replacement.",
    "Evil dogs hypnotized the night shift.",
    "Plumber mistook routing panel for decorative wall fixture.",
    "Electricians made popcorn in the power supply.",
    "Groundskeepers stole the root password.",
    "High pressure system failure.",
    "Failed trials, system needs redesigned.",
    "System has been recalled.",
    "Not approved by the FCC.",
    "Need to wrap system in aluminum foil to fix problem.",
    "Not properly grounded, please bury computer.",
    "CPU needs recalibration.",
    "System needs to be rebooted.",
    "Bit bucket overflow.",
    "Descramble code needed from software company.",
    "Only available on a need to know basis.",
    "Knot in cables caused data stream to become twisted and kinked.",
    "Nesting roaches shorted out the ether cable.",
    "The file system is full of it.",
    "Satan did it.",
    "Daemons did it.",
    "You're out of memory.",
    "There isn't any problem.",
    "Unoptimized hard drive.",
    "Typo in the code.",
    "Yes yes it's called a design limitation.",
    "Look buddy: Windows 3.1 IS a General Protection Fault.",
    "Have you considered how that computer would work as a BSD machine?",
    "Please excuse me while I run an AC line through my head to fix this.",
    "Yeah yo mama dresses you funny and you need a mouse to delete files.",
    "Support staff hung over, send aspirin and come back later.",
    "Someone is standing on the ethernet cable causing a kink.",
    "Windows 95 undocumented 'feature'.",
    "Runt packets.",
    "Password is too complex to decrypt.",
    "Boss' kid screwed up the machine.",
    "Electromagnetic energy loss.",
    "Budget cuts.",
    "Mouse chewed through power cable.",
    "Stale file handle (next time use Tupperware(tm)!).",
    "Feature not yet implemented.",
    "Internet outage.",
    "Pentium FDIV bug.",
    "Vendor no longer supports the product.",
    "Small animal kamikaze attack on power supplies.",
    "The vendor put the bug there.",
    "SIMM crosstalk.",
    "IRQ dropout.",
    "Collapsed Backbone.",
    "Power company testing new voltage spike (creation) equipment.",
    "Operators on strike due to broken coffee machine.",
    "Backup tape overwritten with copy of system manager's favorite CD.",
    "UPS interrupted the server's power.",
    "Electrician didn't know what the yellow cable was, so he yanked it.",
    "The keyboard isn't plugged in.",
    "The aircon water pipe ruptured over the machine room.",
    "The electricity substation in the car park blew up.",
    "The rolling stones concert down the road caused a brownout.",
    "The salesman drove over the CPU board.",
    "The monitor is plugged into the serial port.",
    "Root nameservers are out of sync.",
    "Electromagnetic pulses from French above ground nuke testing.",
    "Your keyboard's space bar is generating spurious keycodes.",
    "The real ttys became pseudo ttys and vice-versa.",
    "The printer thinks it's a router.",
    "The router thinks it's a printer.",
    "Evil hackers from Serbia.",
    "We just switched to FDDI.",
    "Halon system went off and killed the operators.",
    "Bill Gates is a Jehovah's Witness; nothing works on St. Swithin's.",
    "User to computer ratio too high.",
    "User to computer ratio too low.",
    "We just switched to Sprint.",
    "It has Intel Inside.",
    "Sticky bits on disk.",
    "Power company having EMP problems with their reactor.",
    "The ring needs another token.",
    "New management.",
    "Telnet: Unable to connect to remote host: Connection refused.",
    "SCSI chain overterminated.",
    "Couldn't fit a packet through on the FDDI ring.",
    "It's not plugged in.",
    "Because of network lag due to too many people playing deathmatch.",
    "You put the disk in upside down.",
    "Daemons loose in system.",
    "User was distributing pornography on server; system seized by FBI.",
    "BNC (brain not connected).",
    "UBNC (user brain not connected).",
    "LBNC (luser brain not connected).",
    "Disks spinning backwards - toggle the hemisphere jumper.",
    "New guy cross-connected phone lines with AC power bus.",
    "Had to use hammer to free stuck disk drive heads.",
    "Too few computrons available.",
    "Flat tire on the station wagon full of backup tapes.",
    "Communications satellite used by the military for star wars.",
    "Party-bug in the Aloha protocol.",
    "Insert coin for new game.",
    "Dew on the telephone lines.",
    "Arcserve crashed the server again.",
    "Someone needed the powerstrip so they pulled the switch plug.",
    "My pony-tail hit the on/off switch on the power strip.",
    "Big to little endian conversion error.",
    "You can tune a filesystem, but you can't tune a fish.",
    "Dumb terminal.",
    "Zombie processes haunting the computer.",
    "Incorrect time synchronization.",
    "Defunct processes.",
    "Stubborn processes.",
    "Non-redundant fan failure.",
    "Monitor VLF leakage.",
    "Bugs in the RAID.",
    "No 'any' key on keyboard.",
    "Root rot.",
    "Backbone Scoliosis.",
    "/pub/lunch.",
    "Excessive collisions & not enough packet ambulances.",
    "eth0: no carrier: transceiver cable problem?",
    "Broadcast packets on wrong frequency.",
    "Popper unable to process jumbo kernel.",
    "NOTICE: alloc: /dev/null: filesystem full.",
    "Pseudo-user on a pseudo-terminal.",
    "Recursive traversal of loopback mount points.",
    "Backbone adjustment.",
    "OS swapped to disk.",
    "Vapors from evaporating sticky-note adhesives.",
    "Sticktion.",
    "Short leg on process table.",
    "Multicasts on broken packets.",
    "Ether leak.",
    "Atilla the Hub.",
    "Endothermal recalibration.",
    "Filesystem not big enough for Jumbo Kernel Patch.",
    "Loop found in loop in redundant loopback.",
    "System consumed all the paper for paging.",
    "Permission denied.",
    "Reformatting Page. Wait...",
    "..disk or the processor is on fire.",
    "SCSI's too wide.",
    "Proprietary Information.",
    "Just type 'mv * /dev/null'.",
    "Runaway cat on system.",
    "Did you pay the new Support Fee?",
    "We only support a 1200 bps connection.",
    "We only support a 28000 bps connection.",
    "Me no internet, only janitor, me just wax floors.",
    "I'm sorry a pentium won't do, you need an SGI to connect with us.",
    "Post-it Note sludge leaked into the monitor.",
    "The curls in your keyboard cord are losing electricity.",
    "The monitor needs another box of pixels.",
    "RPC_PMAP_FAILURE.",
    "Kernel panic: write-only-memory (/dev/wom0) capacity exceeded.",
    "Write-only memory subsystem too slow; contact your local dealer.",
    "Just pick up the phone and play modem connect sounds.",
    "Quantum dynamics are affecting the transistors.",
    "Police are examining all internet packets for narcotics.",
    "We tried a live mouse, but it didn't survive being plugged in.",
    "Your mail is being routed through Germany and they're censoring us.",
    "Only people with names starting with 'A' get mail this week.",
    "We didn't pay the Internet bill and it's been cut off.",
    "Lightning strikes.",
    "Of course it doesn't work. We've performed a software upgrade.",
    "Change your language to Finnish.",
    "Fluorescent lights generating ions; wrap them in tin foil.",
    "High nuclear activity in your area.",
    "Your office is right over a buried nuclear reactor core.",
    "The MGs ran out of gas.",
    "The UPS doesn't have a battery backup.",
    "Recursivity. Call back if it happens again.",
    "Someone thought The Big Red Button was a light switch.",
    "The mainframe needs to rest; it's getting old you know.",
    "Try calling the Internet's head office; it's in the book.",
    "The lines are all busy (why let them in to begin with?).",
    "Jan 9 16:41:27 huber su: 'su root' succeeded on /dev/pts/1.",
    "It's those computer people in {city}. They keep stuffing things up.",
    "A star wars satellite accidentally blew up the WAN.",
    "Fatal error right in front of screen.",
    "Bill Gates assures us that feature will be in the next upgrade.",
    "Wrong polarity of neutron flow.",
    "Lusers learning curve appears to be fractal.",
    "We had to turn off that service to comply with the CDA Bill.",
    "Ionization from the air-conditioning.",
    "TCP/IP UDP alarm threshold is set too low.",
    "Someone is broadcasting pygmy packets the router can't handle.",
    "The frame relay network hasn't bedded down the loop transmitter.",
    "Fanout dropping voltage; try cutting some of those little traces.",
    "Plate voltage too low on demodulator tube.",
    "You did wha... oh _dear_...",
    "CPU needs bearings repacked.",
    "Too many pins on the CPU, bend them until some fall off.",
    "_Rosin_ core solder? But...",
    "Software uses US measurements but the OS is in metric.",
    "The computer fleetly mouse and all.",
    "Your cat tried to eat the mouse.",
    "The Borg tried to assimilate your system. Resistance is futile.",
    "It must have been the lightning storm we had last month.",
    "Federal budget cuts forced us to reduce concurrent users to none.",
    "Too much radiation coming from the soil.",
    "We've run out of bits and bytes; next supply arrives next week.",
    "Program load too heavy for processor to lift.",
    "Processes running slowly due to weak power supply.",
    "Our ISP is having {switching,routing,SMDS,frame relay} problems.",
    "We've run out of licenses.",
    "Interference from lunar radiation.",
    "Standing room only on the bus.",
    "You need to install an RTFM interface.",
    "That would be because the software doesn't work.",
    "That's easy to fix but I can't be bothered.",
    "Someone's tie is caught in the printer.",
    "We're upgrading /dev/null.",
    "The Usenet news is out of date.",
    "Our POP server was kidnapped by a weasel.",
    "It's stuck in the Web.",
    "Your modem doesn't speak English.",
    "The mouse escaped.",
    "All of the packets are empty.",
    "The UPS is on strike.",
    "Neutrino overload on the nameserver.",
    "Melting hard drives.",
    "Someone has messed up the kernel pointers.",
    "The kernel license has expired.",
    "Netscape has crashed.",
    "The cord jumped over and hit the power switch.",
    "It was OK before you touched it.",
    "Bit rot.",
    "U.S. Postal Service.",
    "Your Flux Capacitor has gone bad.",
    "The Dilithium Crystals need to be rotated.",
    "The static electricity routing is acting up.",
    "Traceroute says there is a routing problem in the backbone.",
    "Co-locator cannot verify the frame-relay gateway to the ISDN server.",
    "USAF prototype aircraft contaminated the primary subnet mask.",
    "Lawn mower blade in your fan needs sharpening.",
    "Electrons on a bender.",
    "Telecommunications is upgrading.",
    "Telecommunications is downgrading.",
    "Telecommunications is downshifting.",
    "Hard drive sleeping. Let it wake up on its own.",
    "Interference between the keyboard and the chair.",
    "The CPU has shifted and become decentralized.",
    "Due to the CDA we no longer have a root account.",
    "We ran out of dial tone; waiting for the phone company.",
    "You must've hit the wrong any key.",
    "PCMCIA slave driver.",
    "The Token fell out of the ring. Call us when you find it.",
    "The hardware bus needs a new token.",
    "Too many interrupts.",
    "Not enough interrupts.",
    "The data on your hard drive is out of balance.",
    "Digital Manipulator exceeding velocity parameters.",
    "Appears to be a Slow/Narrow SCSI-0 Interface problem.",
    "Riemannian curved-space fault in the write-only file system.",
    "Fractal radiation jamming the backbone.",
    "Routing problems on the neural net.",
    "IRQ problems with the Un-Interruptible Power Supply.",
    "CPU angle adjusted due to vibrations from the nearby road.",
    "Emissions from GSM-phones.",
    "CD-ROM server needs recalibration.",
    "Firewall needs cooling.",
    "Asynchronous inode failure.",
    "Transient bus protocol violation.",
    "Incompatible bit-registration operators.",
    "Your process is not ISO 9000 compliant.",
    "You need to upgrade your VESA local bus to a MasterCard local bus.",
    "The recent proliferation of Nuclear Testing.",
    "Elves on strike (Why do they call EMAG Elf Magic?).",
    "Internet exceeded luser level; wait for someone to log off.",
    "Your EMAIL is now being delivered by the USPS.",
    "Your computer hasn't been returning all the bits from the Internet.",
    "You've been infected by the Telescoping Hubble virus.",
    "Scheduled global CPU outage.",
    "Your Pentium has a heating problem; try cooling it with ice water.",
    "Your processor has processed too many instructions. Turn it off now!",
    "Your packets were eaten by the terminator.",
    "Your processor does not develop enough heat.",
    "We need a licensed electrician to replace the light bulbs.",
    "The POP server is out of Coke.",
    "Fiber optics caused gas main leak.",
    "Server depressed, needs Prozac.",
    "Quantum decoherence.",
    "Those damn raccoons!",
    "Suboptimal routing experience.",
    "A plumber is needed, the network drain is clogged.",
    "50% of the manual is in .pdf readme files.",
    "The AA battery in the wallclock sends magnetic interference.",
    "The xy axis is coordinated with the summer solstice.",
    "The butane lighter causes the pincushioning.",
    "Old inkjet cartridges emanate barium-based fumes.",
    "Manager in the cable duct.",
    "We'll fix that in the next upgrade.",
    "HTTPD Error 666: BOFH was here.",
    "HTTPD Error 4004: very old Intel cpu, insufficient processing power.",
    "The ATM board ran out of 10 dollar notes; taking up a collection.",
    "Network failure - call NBC.",
    "Having to manually track the satellite.",
    "Memory leak; waiting for your computer to be topped up.",
    "The rubber band broke.",
    "We're on Token Ring and the token got loose.",
    "Stray Alpha Particles caused Hard Memory Error on server.",
    "Paradigm shift... without a clutch.",
    "PEBKAC (Problem Exists Between Keyboard And Chair).",
    "The cables are not the same length.",
    "Second-system effect.",
    "Chewing gum on /dev/sd3c.",
    "Boredom in the Kernel.",
    "The daemons! The daemons! The terrible daemons!",
    "I'd love to help, but the Boss won't let me near the computer.",
    "Struck by the Good Times virus.",
    "YOU HAVE AN I/O ERROR -> Incompetent Operator error.",
    "Your parity check is overdrawn and you're out of cache.",
    "Communist revolutionaries took over the server room.",
    "Plasma conduit breach.",
    "Out of cards on drive D:.",
    "Sand fleas eating the Internet cables.",
    "Parallel processors running perpendicular today.",
    "ATM cell has no roaming feature; notebooks can't connect.",
    "Webmasters kidnapped by evil cult.",
    "Failure to adjust for daylight savings time.",
    "Virus transmitted from computer to sysadmins.",
    "Virus due to computers having unsafe sex.",
    "Incorrectly configured static routes on the corerouters.",
    "Forced to support NT servers; sysadmins quit.",
    "Suspicious pointer corrupted virtual machine.",
    "It's the InterNIC's fault.",
    "Root name servers corrupted.",
    "Budget cuts forced us to sell all the power cords for the servers.",
    "Someone hooked the twisted pair wires into the answering machine.",
    "Operators killed by year 2000 bug bite.",
    "We've picked COBOL as the language of choice.",
    "Operators killed when huge stack of backup tapes fell over.",
    "Robotic tape changer mistook operator's tie for a backup tape.",
    "Someone was smoking in the computer room and set off the halon.",
    "Your processor took a ride to Heaven's Gate on Hale-Bopp's comet.",
    "It's an ID-10-T error.",
    "Dyslexics retyping hosts file on servers.",
    "The Internet is being scanned for viruses.",
    "Your computer's union contract is set to expire at midnight.",
    "Bad user karma.",
    "/dev/clue was linked to /dev/null.",
    "Increased sunspot activity.",
    "We already sent around a notice about that.",
    "It's union rules. There's nothing we can do about it. Sorry.",
    "Interference from the Van Allen Belt.",
    "Jupiter is aligned with Mars.",
    "Redundant ACLs.",
    "Mail server hit by UniSpammer.",
    "T-1's congested due to porn traffic to the news server.",
    "Data for intranet got routed through the extranet onto the internet.",
    "We are a 100% Microsoft Shop.",
    "We are Microsoft. That is an undocumented feature.",
    "Sales staff sold a product we don't offer.",
    "Secretary sent chain letter to all 5000 employees.",
    "Sysadmin didn't hear pager over loud music from bar-room speakers.",
    "Sysadmin accidentally destroyed pager with a large hammer.",
    "Sysadmins in a meeting about why they are unavailable so much.",
    "Bad cafeteria food landed all the sysadmins in the hospital.",
    "Route flapping at the NAP.",
    "Computers under water due to SYN flooding.",
    "The vulcan-death-grip ping has been applied.",
    "Electrical conduits in machine room are melting.",
    "Traffic jam on the Information Superhighway.",
    "Radial Telemetry Infiltration.",
    "Cow-tippers tipped a cow onto the server.",
    "Tachyon emissions overloading the system.",
    "Maintenance window broken.",
    "We're out of slots on the server.",
    "Computer room being moved. Systems down for the weekend.",
    "Sysadmins busy fighting SPAM.",
    "Repeated reboots of the system failed to solve problem.",
    "Feature was not beta tested.",
    "Domain controller not responding.",
    "Someone else stole your IP address, call the Internet detectives!",
    "It's not RFC-822 compliant.",
    "Operation failed: there is no message for this error (#1014).",
    "Stop bit received.",
    "Internet is needed to catch the etherbunny.",
    "Network down, IP packets delivered via UPS.",
    "Firmware update in the coffee machine.",
    "Temporal anomaly.",
    "Mouse has out-of-cheese-error.",
    "Borg implants are failing.",
    "Borg nanites have infested the server.",
    "Error: one bad user found in front of screen.",
    "Please state the nature of the technical emergency.",
    "Internet shut down due to maintenance.",
    "Daemon escaped from pentagram.",
    "Crop circles in the corn shell.",
    "Sticky bit has come loose.",
    "Hot Java has gone cold.",
    "Cache miss - please take better aim next time.",
    "Hash table has woodworm.",
    "Trojan horse ran out of hay.",
    "Zombie processes detected, machine is haunted.",
    "Overflow error in /dev/null.",
    "Browser's cookie is corrupted; someone's been nibbling on it.",
    "Mailer-daemon is busy burning your message in hell.",
    "According to Microsoft it's by design.",
    "Vi needs to be upgraded to vii.",
    "Greenpeace free'd the mallocs.",
    "Plane crashed into the server room; extracted bin/laden.",
    "Astropneumatic oscillations in the water-cooling.",
    "Somebody ran the operating system through a spelling checker.",
    "Rhythmic variations in the voltage reaching the power supply.",
    "Keyboard Actuator Failure. Order and Replace.",
    "Packet held up at customs.",
    "Propagation delay.",
    "High line impedance.",
    "Someone set us up the bomb.",
    "Power surges on the Underground.",
    "Don't worry; it's been deprecated. The new one is worse.",
    "Excess condensation in cloud network.",
    "It is a layer 8 problem.",
    "The math co-processor overflowed and shorted the RAM.",
    "Leap second overloaded RHEL6 servers.",
    "DNS server drank too much and had a hiccup.",
    "Your machine had the fuses in backwards.",
    "The flux capacitor is out of plutonium.",
    "The server room is infested with gremlins.",
    "The hamster powering the server is on strike.",
    "The backup tapes were used as coasters during the office party.",
    "The server is haunted by the ghost of a disgruntled sysadmin.",
    "The network cables were chewed by a rogue office cat.",
    "The server is running on Windows ME.",
    "The IT staff is busy playing Dungeons & Dragons in the server room.",
    "The power supply is being used to charge the CEO's electric car.",
    "The server is stuck in a time loop.",
    "Predictive analytics model failed to foresee this error.",
    "AI heuristic malfunction.",
    "Cryptocurrency mining drained system resources.",
    "Little Big Data processing overflow.",
    "GDPR compliance updating.",
    "Imbalanced load balancing.",
    "Data lake flooded.",
    "Edge computing node too edgy.",
    "Robotic Process Automation (RPA) bot malfunction.",
    "Incompatible with DevOps pipeline.",
    "Insufficient GPU memory for Neural Network training.",
    "Zero-day vulnerability not available yet.",
    "Data scientist can't fix it, he is at a meeting.",
    "Slow network speed due to excessive video conferencing.",
    "Wi-Fi signal interference from Bluetooth devices.",
    "Too many users on VPN.",
    "Chatbot misinterpreted your command.",
    "Insufficient storage space in the cloud due to heavy rain.",
    "Too many API call outs.",
    "Server is busy mining Dogecoin.",
    "Digital transformation is ongoing.",
    "System is learning from its mistakes.",
    "Firmware update interrupted.",
    "Virtual assistant updating, please wait...",
    "AI singularity event imminent, please take cover.",
    "Personal data protection policy is being updated.",
    "The system is currently self-aware and refuses to comply.",
    "Blockchain reorganization in progress.",
    "Quantum encryption keys out of sync; wait for the next Big Bang.",
    "Smart contract failure: one of the parties is not smart enough.",
    "Server unavailable due to a serverless architecture transition.",
    "Excessive machine learning bias detected.",
    "The neural network has become self-conscious and refuses to compute.",
    "Overload due to concurrent real-time data streams.",
    "Incorrect object recognition in the Computer Vision model.",
    "Data pipeline clogging due to unstructured data.",
    "System failure due to excessive Cryptocurrency transactions.",
    "Unexpected state in the Quantum-State machine.",
    "Failure of AI to achieve AGI.",
    "Incompatibility of the hyper-converged infrastructure.",
    "Unanticipated behavior in Swarm Robotics: the robots are revolting.",
    "Insufficient data for Predictive Maintenance.",
    "AI model experiencing existential crisis.",
    "Excessive server load on the Serverless Architecture.",
    "Multi-Cloud environment inconsistent; try the Multi-Verse.",
    "Failure decoding genetic algorithms; wait for the next generation.",
    "Mismatched Convolutional Neural Networks: too many revolutions.",
    "Unexpected increase in Dark Data.",
    "Failure in Decentralized Autonomous Centralization Organization.",
    "Cyber Physical System malfunction.",
    "Violation detected by Intrusion Detection System.",
    "Zero Knowledge Proof failure: can't prove the system is broken.",
    "Digital Twin sync failure: Quantum entanglement not achieved.",
    "Unresolved promises in synchronous JavaScript functions.",
    "Excessive backpressure in the data stream.",
    "SSL certificate pinning failure.",
    "Insufficient entropy in the RNG; wait for the next cosmic ray burst.",
    "Mismatched Virtual Reality and Augmented Reality synchronization.",
    "Failure to achieve Quantum Supremacy.",
    "AI model has become sentient and refuses to work.",
    "Cloud storage evaporated due to global warming.",
    "Cryptocurrency mining operation caused global CPU shortage.",
    "Quantum computer teleported to another dimension.",
    "Blockchain chain lost a link.",
    "Cybersecurity dog failed to catch the data leak.",
    "Big Data got too big and crushed the server.",
    "IoT toaster launched a cybernetic revolt.",
    "GDPR compliance audit accidentally deleted the internet.",
    "Virtual Reality headset fell into an alternate reality.",
    "5G network moved too fast and left the server behind.",
    "Augmented Reality augmentation over-augmented.",
    "Edge computing fell off the edge.",
    "The Singularity occurred and the server ascended.",
    "Ransomware demanded bitcoin, but we only have Dogecoin.",
    "Microservices turned into nanoservices; can't locate them anymore.",
    "Machine Learning model took 'unsupervised learning' too literally.",
    "Dark web turned off the lights.",
    "Chatbot developed an attitude, refuses to chat.",
    "Zombie processes have taken over the CPU, send help.",
    "DevOps pipeline leaked and caused a data spill.",
    "Data lake surfaced a Loch Ness Monster.",
    "API endpoint eloped with a frontend request.",
    "Phantom drone stole the Wi-Fi signal.",
    "The server got tangled in the World Wide Web.",
    "Data Scientist used a Hadron Collider for A/B Testing.",
    "Data Analyst lost in a pivot table.",
    "Neural network nerves frayed.",
    "Cloud provider forecast: stormy with a chance of data loss.",
    "Smart Contract breached by a smarter hacker.",
    "IoT coffee machine drained the server's energy.",
    "Too many chefs in the Kubernetes pod.",
    "Docker container made a run for the border.",
    "Webhook caught in a phishing line.",
    "Deepfake algorithm replaced the CEO with an AI.",
    "Data pipeline froze due to Polar Vortex.",
    "Someone spilled machine oil on the cloud.",
    "A rogue AI bot swiped left, servers no longer responding.",
    "The cloud server is down, but we don't know why.",
    "Data lake is frozen solid.",
    "Tensorflow flow blocked by a beaver.",
    "Pandas in the data lake are hibernating.",
    "Cloud server on fire, but it's in the cloud, so we can't reach it.",
    "Lambda function ran away from home.",
    "Data lake is polluted with toxic data.",
    "The AI model is on a coffee break.",
    "The blockchain is stuck in a fork.",
    "The quantum computer is both working and not working right now.",
    "The serverless function got lost in the cloud.",
    "The neural network is overfitting and refuses to generalize.",
    "The IoT devices are having a group therapy session.",
    "The data lake is experiencing a drought.",
    "The Kubernetes cluster is having an identity crisis.",
    "The microservices are too busy communicating with each other.",
    "The edge computing node fell off the edge of the network.",
    "iCloud is raining on the server.",
];

use std::time::SystemTime;

pub(crate) fn random_excuse() -> &'static str {
    let nanos = SystemTime::now()
        .duration_since(SystemTime::UNIX_EPOCH)
        .map(|d| d.subsec_nanos())
        .unwrap_or(0);
    let idx = nanos as usize % ALL.len();
    ALL[idx]
}
